version: '3.8'

services:
  backend:
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JWT_SECRET: yourSuperSecretKeyMustBeAtLeast32BytesLong...
      JWT_EXPIRATION: 4000000
      JWT_REFRESH_EXPIRATION: 604800000
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hospital_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234