version: '3.8'

services:
  backend:
    image: mustafaguler4/doctor-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hospital_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

  mysql:
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: