spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: update   # create, create-drop, validate, update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # E?er flyway/liquibase migration kullanacaksan onlar? da ekleyebilirsin
  # flyway:
  #   enabled: true
  #   locations: classpath:db/migration