spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  secret: yourSuperSecretKeyMustBeAtLeast32BytesLongsdasdasdasd!!!
  expiration: 3600000
  refresh:
    expiration: 604800000