spring:
  datasource:
    url: jdbc:postgresql://dpg-d6u52cggjchc73cqggeg-a:5432/hospital_db_3all
    username: hospital_db_3all_user
    password: qQDNNE4FxxWIuMrtyBEhejvnGM6zJ7v7

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:8080}