spring:
  datasource:
    url: jdbc:postgresql://dpg-xxxx:5432/hospital_db_3all
    username: hospital_db_3all_user
    password: qQDNNE4FxxWIuMrtyBEhejvnGM6zJ7v7
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect